### ISSUE TITLE
1.20.1 Update?

### ISSUE THREAD

**Issue by Aabaddon** [craisinlord/Integrated-Stronghold#3]
i've made a modpack to play with friends and we wanted to rent a server to host it, but we all agreed that the modpack is not complete without integrated stronghold, i wanted to ask if you're going to update it soon or if you dont have plans to keep mantaining it (this also lets us know if we should install quark or not because is a bit of an annoying mod and if we dont have integrated stronghold then there is no reason to install it)

**Comment by craisinlord** [comment]
It's coming! Been working on porting the api, it'll be done by the end of the month for sure

**Comment by Aabaddon** [comment]
thank u!
